### ISSUE TITLE
How to populate study

### ISSUE THREAD

**Issue by Hidayat722** [optuna/optuna-dashboard#37]
Hi,
i am new to optuna dashboard. i have tensorboard logs for my trials but i don't understand how to populate optuna-dashboard with my study. Any help would be appreciated.

thanks.

**Comment by breznak** [comment]
Hi, 

I am having the same problem. Installed `optuna-dashboard` and the webUI shows up. 

It would be nice if it could list already existing studies. 
I'm using optuna+pytorch-lightning and automated logger to tb. 

My logs are structured as 
```
$ ls outputs/2021-03-18/11-03-23/
main.log  saved_models  tb_logdir
```

Any help much appreciated!

**Comment by Hidayat722** [comment]
Hi @breznak  Actually it doesn't work that way. there are two different things storage and study. So basically storage is sqlite db where study is created and saved. To visualize the study you have to call 

optuna-dashboard sqlite:///test.db    # where test.db is name of the storage 

here is a simple example

```python
pruner = optuna.pruners.MedianPruner(n_startup_trials=3)

    study = optuna.create_study(
        direction='maximize',
        pruner=pruner,
        study_name="example_study",
        storage="test.db,
        load_if_exists=True
    )

    study.optimize(
        opt.objective, n_trials=30,
        callbacks=[sample_callback]
    )

```

**Comment by breznak** [comment]
Appreciate the helpful answer, thank you! 

For the refenrence, I'm using `hydra-sweeper-optuna` plugin with example config as 
```
 @package hydra.sweeper
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
optuna_config:
  direction: minimize
  study_name: my_experiment
  storage: sqlite:///example.db
  n_trials: 3
  n_jobs: 2
  sampler: tpe
  seed: 123

search_space:
  optimizer.params.lr:
    type: categorical
    choices: [ 1e-3, 1e-2, 1e-1 ]
```
And after your suggested modification
> storage: sqlite:///example.db 

this works well! :+1: 
I fist though that the `test.db` is a file, not a URI `sqlite:///test.db` 

Maybe add your example the the Readme, so people can easily try your dashboard?
