### ISSUE TITLE
npm run build:dev fails with "[webpack-cli] Uncaught exception: TypeError: Cannot read property 'compiler' of undefined"

### ISSUE THREAD

**Issue by simonhessner** [optuna/optuna-dashboard#89]
# Bug reports

I would like to contribute some improvements to the UI and was trying to follow the [contribution manual](https://github.com/optuna/optuna-dashboard/blob/main/DEVELOPMENT.md). I use Ubuntu with node v14.16.1 and npm v6.14.12. Typescript version is 4.2.4.

This is the error I get when running **npm run build:dev**:

> > goptuna-dashboard@0.0.1 build:dev /home/simon/projects/optuna-dashboard
> > NODE_ENV=development webpack
> 
> = = = = = = = = = = = = = = = = = = =
> DEVELOPMENT BUILD
> = = = = = = = = = = = = = = = = = = =
> [webpack-cli] Uncaught exception: TypeError: Cannot read property 'compiler' of undefined
> [webpack-cli] TypeError: Cannot read property 'compiler' of undefined
>     at /home/simon/projects/optuna-dashboard/node_modules/ts-loader/dist/after-compile.js:13:25
>     at /home/simon/projects/optuna-dashboard/node_modules/ts-loader/dist/instances.js:259:84
>     at Hook.eval [as call] (eval at create (/home/simon/projects/optuna-dashboard/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
>     at Hook.CALL_DELEGATE [as _call] (/home/simon/projects/optuna-dashboard/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
>     at /home/simon/projects/optuna-dashboard/node_modules/webpack/lib/Compilation.js:2469:40
>     at eval (eval at create (/home/simon/projects/optuna-dashboard/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
>     at eval (eval at create (/home/simon/projects/optuna-dashboard/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
>     at /home/simon/projects/optuna-dashboard/node_modules/webpack/lib/SourceMapDevToolPlugin.js:546:10
>     at /home/simon/projects/optuna-dashboard/node_modules/neo-async/async.js:2830:7
>     at Object.each (/home/simon/projects/optuna-dashboard/node_modules/neo-async/async.js:2857:9)

Are there other dependencies that are not mentioned in DEVELOMENT.md?

**Comment by c-bata** [comment]
Hi! I'm glad to see that there is interest to contribute.

> Are there other dependencies that are not mentioned in DEVELOMENT.md?

No. optuna-dashboard is continuously built on GitHub Actions like the following.

```
  build:
    name: JS build check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Set up Node v14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build:dev
          npm run build:prd
```

https://github.com/optuna/optuna-dashboard/blob/main/.github/workflows/typescript-checks.yml#L28-L44

As you can see, it uses an Ubuntu image. So I'm sorry that I'm not sure why it raises an error in your environment.
